CREATE TABLE IF NOT EXISTS product_types (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS brands (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(150) UNIQUE NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL
);

ALTER TABLE products 
ADD COLUMN IF NOT EXISTS internal_code VARCHAR(100) UNIQUE,
ADD COLUMN IF NOT EXISTS product_type_id BIGINT REFERENCES product_types(id),
ADD COLUMN IF NOT EXISTS brand_id BIGINT REFERENCES brands(id);

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS avatar_url TEXT;

